import Head from 'next/head';
import React from 'react';
import Header from './Header';
import Footer from './Footer';

export default function Layout({ children }) {
	return (
		<div>
			<Head>
				<title>login node project</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="min-h-screen h-full flex flex-col">
				<Header />
				{children}
				<Footer />
			</main>
		</div>
	);
}
